spring:
  application:
    name: brewery-inventory-failover-service
  main:
    web-application-type: reactive

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://netflix:eureka@localhost:8761/eureka
